# Generated by Django 5.2.3 on 2025-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_otp_customuser_otp_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="transaction_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
