# Generated by Django 5.2.3 on 2025-11-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="encrypted_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
