# Generated by Django 5.2.3 on 2025-07-04 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="updated_at",
        ),
    ]
