# Generated by Django 5.2.3 on 2025-07-04 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_remove_wallet_created_at_remove_wallet_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
